[2025-01-16T21:25:46.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-16T21:25:46.758+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-16T21:25:31.551667+00:00 [queued]>
[2025-01-16T21:25:46.797+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-16T21:25:31.551667+00:00 [queued]>
[2025-01-16T21:25:46.799+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-16T21:25:46.863+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_file_task> on 2025-01-16 21:25:31.551667+00:00
[2025-01-16T21:25:46.895+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2577) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-16T21:25:46.899+0000] {standard_task_runner.py:72} INFO - Started process 2582 to run task
[2025-01-16T21:25:46.909+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'detect_data_drift_notify_retrain', 'detect_file_task', 'manual__2025-01-16T21:25:31.551667+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpuez48nl6']
[2025-01-16T21:25:46.925+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask detect_file_task
[2025-01-16T21:25:47.184+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-16T21:25:31.551667+00:00 [running]> on host 75b771cd017c
[2025-01-16T21:25:47.608+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RL' AIRFLOW_CTX_DAG_ID='detect_data_drift_notify_retrain' AIRFLOW_CTX_TASK_ID='detect_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T21:25:31.551667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T21:25:31.551667+00:00'
[2025-01-16T21:25:47.609+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-16T21:25:47.727+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-16T21:25:47.814+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-01-16T21:25:49.764+0000] {monitoring-dag.py:46} INFO - Checking file in S3: s3://covertype-final-project-jedha/covertype/new_data/covtype_sample_drift.csv
[2025-01-16T21:25:49.766+0000] {monitoring-dag.py:51} ERROR - Error checking S3: Parameter validation failed:
Invalid bucket name "s3://covertype-final-project-jedha": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2025-01-16T21:25:49.769+0000] {python.py:240} INFO - Done. Returned value was: no_file_found_task
[2025-01-16T21:25:49.771+0000] {branch.py:38} INFO - Branch into no_file_found_task
[2025-01-16T21:25:49.771+0000] {skipmixin.py:230} INFO - Following branch ('no_file_found_task',)
[2025-01-16T21:25:49.895+0000] {skipmixin.py:278} INFO - Skipping tasks [('detect_data_drift_task', -1)]
[2025-01-16T21:25:50.113+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-16T21:25:50.114+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_data_drift_notify_retrain, task_id=detect_file_task, run_id=manual__2025-01-16T21:25:31.551667+00:00, execution_date=20250116T212531, start_date=20250116T212546, end_date=20250116T212550
[2025-01-16T21:25:50.168+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-16T21:25:50.301+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T21:25:50.319+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
